version: "3.7"

services:
  elm-test-rs:
    image: gcr.io/fir-sandbox-326008/lamdera-ci:latest
    working_dir: /build
    networks:
      - lamdera-ci-network
    command: ./.cloudbuild/bin/elm-test-rs

  add-lamdera-remote-to-git:
    image: gcr.io/fir-sandbox-326008/lamdera-ci:latest
    working_dir: /build
    networks:
      - lamdera-ci-network
    command: |
      git remote add lamdera git@apps.lamdera.com:fir-sandbox-2.git
      git remote --fetch

  lamdera-check:
    image: gcr.io/fir-sandbox-326008/lamdera-ci:latest
    working_dir: /build
    networks:
      - lamdera-ci-network
    command: git remote -v

networks:
  lamdera-ci-network:
    driver: bridge
    ipam:
      driver: default