version: "3.7"

services:
  elm-test-rs:
    image: gcr.io/fir-sandbox-326008/lamdera-ci:latest
    working_dir: /build
    networks:
      - lamdera-ci-network
    command: ./.cloudbuild/bin/elm-test-rs

  add-lamdera-remote-to-git:
    image: gcr.io/fir-sandbox-326008/lamdera-ci:latest
    working_dir: /build
#    volumes:
#      - $HOME/.ssh/id_ed25519:/root/.ssh/id_ed25519
#      - $HOME/.ssh/id_ed25519.pub:/root/.ssh/id_ed25519.pub
    networks:
      - lamdera-ci-network
    command: bash
#      git remote add lamdera git@apps.lamdera.com:fir-sandbox-2.git
#      git remote --fetch

  lamdera-check:
    image: gcr.io/fir-sandbox-326008/lamdera-ci:latest
    working_dir: /build
    networks:
      - lamdera-ci-network
    command: git remote -v

networks:
  lamdera-ci-network:
    driver: bridge
    ipam:
      driver: default