FROM node:16-slim

RUN apt-get update
RUN apt-get install -y \
    curl \
    libtinfo5 \
    git \
    wget \
    xdg-utils  # <-- this package is very hefty and a whopping 319MB! But is required for lamdera login

# create directory to work in
RUN mkdir /build
WORKDIR /build
COPY ./ .

# install rust, see: https://www.rust-lang.org/tools/install
# NB: We wget / save the file so that the -y flag can be passed in.
RUN wget -O install_rust.sh https://sh.rustup.rs
RUN chmod +x install_rust.sh
RUN ./install_rust.sh -y

# update npm, npm install elm stuff
RUN npm install -g npm
RUN npm install -g elm elm-test elm-review elm-spa

# install Lamdera
RUN curl https://static.lamdera.com/bin/linux/lamdera -o /usr/local/bin/lamdera
RUN chmod a+x /usr/local/bin/lamdera

# Running `lamdera make` has the side-effect of fetching required elm packages.
# This is so elm-test-rs succeeds
RUN elm-spa gen
RUN lamdera make src/Frontend.elm src/Backend.elm
