version: "3.7"

services:
  elm-test-rs:
    image: gcr.io/fir-sandbox-326008/lamdera-ci:latest
    command: ./.cloudbuild/bin/elm-test-rs
    working_dir: /build
    networks:
      - lamdera-ci-network

  shell-cmd:
    image: gcr.io/fir-sandbox-326008/lamdera-ci:latest
    working_dir: /build
    networks:
      - lamdera-ci-network

networks:
  lamdera-ci-network:
    driver: bridge
    ipam:
      driver: default