steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Lamdera CI image
    args: ['build', '-t', 'gcr.io/fir-sandbox-326008/lamdera-ci:latest', '--file', './.cloudbuild/Dockerfile-Ci', '.']

  - id: Pull down Lamdera auth token, save to expected path
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://project-fir-api-maintenance/lamdera-auth-token', '~/.elm/.lamdera-cli' ]

  - id: ssh git public key
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://project-fir-api-maintenance/id_ed25519.pub', '~/.ssh/id_ed25519.pub' ]

  - id: ssh git private key
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://project-fir-api-maintenance/id_ed25519', '~/.ssh/id_ed25519' ]

  # pre-emptive cleanup, in case previous run failed etc
  - name: 'docker/compose:1.29.2'
    dir: '.cloudbuild'
    args: ['down']

  - id: Add `lamdera` remote to git
    name: 'docker/compose:1.29.2'
    dir: '.cloudbuild'
    args: ['run', 'add-lamdera-remote-to-git']

  # run Elm tests
  - name: 'docker/compose:1.29.2'
    dir: '.cloudbuild'
    args: ['run', 'elm-test-rs']

  # run Lamdera check - this validates Evergreen migrations
  - name: 'docker/compose:1.29.2'
    dir: '.cloudbuild'
    args: ['run', 'lamdera-check']

  # clean up after ourselves
  - name: 'docker/compose:1.29.2'
    dir: '.cloudbuild'
    args: ['down']

options:
  pool:
    name: 'projects/fir-sandbox-326008/locations/us-east4/workerPools/pool-1'
